-- =============================================================================
-- V1__schema.sql - SecureBank initial schema.
--
-- Flyway owns the schema. JPA is configured ddl-auto=validate, so the entity
-- mappings must line up exactly with what we create here.
--
-- Money is ALWAYS numeric(19,4): 19 significant digits, 4 after the decimal
-- point. We never use floating point for money because binary floats cannot
-- represent values like 0.10 exactly, which silently corrupts balances. The 4
-- decimal places leave headroom for sub-cent interest / FX maths.
-- =============================================================================

-- ----------------------------------------------------------------------------
-- users: authentication identities. One row per login.
-- 'version' is the optimistic-lock counter (JPA @Version) so concurrent updates
-- to e.g. failed_attempts don't silently clobber each other.
-- ----------------------------------------------------------------------------
CREATE TABLE users (
    id               BIGSERIAL PRIMARY KEY,
    username         VARCHAR(64)  NOT NULL UNIQUE,
    email            VARCHAR(255) NOT NULL UNIQUE,
    password_hash    VARCHAR(255) NOT NULL,
    role             VARCHAR(16)  NOT NULL,           -- CUSTOMER | TELLER | ADMIN
    enabled          BOOLEAN      NOT NULL DEFAULT TRUE,
    failed_attempts  INTEGER      NOT NULL DEFAULT 0,
    locked_until     TIMESTAMPTZ,                     -- null = not locked
    preferred_locale VARCHAR(8)   NOT NULL DEFAULT 'en',
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT chk_users_role CHECK (role IN ('CUSTOMER', 'TELLER', 'ADMIN'))
);

-- ----------------------------------------------------------------------------
-- customers: the human/profile behind a user, plus KYC and address.
-- ----------------------------------------------------------------------------
CREATE TABLE customers (
    id            BIGSERIAL PRIMARY KEY,
    user_id       BIGINT       NOT NULL UNIQUE REFERENCES users (id),
    first_name    VARCHAR(100) NOT NULL,
    last_name     VARCHAR(100) NOT NULL,
    phone         VARCHAR(32),
    date_of_birth DATE,
    kyc_status    VARCHAR(16)  NOT NULL DEFAULT 'PENDING',  -- PENDING | VERIFIED | REJECTED
    address_line  VARCHAR(255),
    city          VARCHAR(100),
    state         VARCHAR(100),
    postal_code   VARCHAR(16),
    country       VARCHAR(64),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_customers_kyc CHECK (kyc_status IN ('PENDING', 'VERIFIED', 'REJECTED'))
);

-- ----------------------------------------------------------------------------
-- accounts: a money container belonging to a customer.
-- 'version' is the optimistic-lock counter that catches lost balance updates.
-- ----------------------------------------------------------------------------
CREATE TABLE accounts (
    id             BIGSERIAL PRIMARY KEY,
    account_number VARCHAR(34)   NOT NULL UNIQUE,        -- IBAN-like, generated by a factory
    customer_id    BIGINT        NOT NULL REFERENCES customers (id),
    type           VARCHAR(16)   NOT NULL,               -- SAVINGS | CURRENT | FIXED_DEPOSIT
    currency       VARCHAR(3)    NOT NULL DEFAULT 'INR',
    balance        NUMERIC(19,4) NOT NULL DEFAULT 0,
    status         VARCHAR(16)   NOT NULL DEFAULT 'ACTIVE', -- ACTIVE | FROZEN | CLOSED
    opened_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version        BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT chk_accounts_type   CHECK (type IN ('SAVINGS', 'CURRENT', 'FIXED_DEPOSIT')),
    CONSTRAINT chk_accounts_status CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED')),
    CONSTRAINT chk_accounts_balance_nonneg CHECK (balance >= 0)
);

CREATE INDEX idx_accounts_customer ON accounts (customer_id);

-- ----------------------------------------------------------------------------
-- transactions: a single money-movement record (the customer-facing view).
-- The double-entry detail lives in ledger_entries; this row is the summary.
-- ----------------------------------------------------------------------------
CREATE TABLE transactions (
    id                      BIGSERIAL PRIMARY KEY,
    reference               VARCHAR(40)   NOT NULL UNIQUE,  -- public id, e.g. TXN-...
    account_id              BIGINT        NOT NULL REFERENCES accounts (id),
    counterparty_account_id BIGINT        REFERENCES accounts (id),  -- null for deposit/withdraw
    type                    VARCHAR(16)   NOT NULL,         -- DEPOSIT | WITHDRAWAL | TRANSFER
    amount                  NUMERIC(19,4) NOT NULL,
    currency                VARCHAR(3)    NOT NULL DEFAULT 'INR',
    status                  VARCHAR(16)   NOT NULL,         -- PENDING | COMPLETED | FAILED | REVERSED
    description             VARCHAR(255),
    balance_after           NUMERIC(19,4),                  -- balance of account_id after the txn
    fraud_score             NUMERIC(5,4),                   -- 0.0000 .. 1.0000
    created_at              TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT chk_txn_type   CHECK (type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER')),
    CONSTRAINT chk_txn_status CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'REVERSED')),
    CONSTRAINT chk_txn_amount_pos CHECK (amount > 0)
);

CREATE INDEX idx_txn_account     ON transactions (account_id);
CREATE INDEX idx_txn_created     ON transactions (created_at);
CREATE INDEX idx_txn_type        ON transactions (type);

-- ----------------------------------------------------------------------------
-- ledger_entries: the double-entry journal. Every balanced money movement
-- writes one DEBIT and one CREDIT leg whose amounts net to zero. This is the
-- accounting source of truth - summing CREDIT minus DEBIT for an account must
-- equal its balance.
-- ----------------------------------------------------------------------------
CREATE TABLE ledger_entries (
    id             BIGSERIAL PRIMARY KEY,
    transaction_id BIGINT        NOT NULL REFERENCES transactions (id),
    account_id     BIGINT        NOT NULL REFERENCES accounts (id),
    direction      VARCHAR(8)    NOT NULL,               -- DEBIT | CREDIT
    amount         NUMERIC(19,4) NOT NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT chk_ledger_direction CHECK (direction IN ('DEBIT', 'CREDIT')),
    CONSTRAINT chk_ledger_amount_pos CHECK (amount > 0)
);

CREATE INDEX idx_ledger_txn     ON ledger_entries (transaction_id);
CREATE INDEX idx_ledger_account ON ledger_entries (account_id);

-- ----------------------------------------------------------------------------
-- beneficiaries: saved payees a customer can transfer to.
-- ----------------------------------------------------------------------------
CREATE TABLE beneficiaries (
    id             BIGSERIAL PRIMARY KEY,
    customer_id    BIGINT       NOT NULL REFERENCES customers (id),
    name           VARCHAR(150) NOT NULL,
    account_number VARCHAR(34)  NOT NULL,
    bank_name      VARCHAR(150),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_beneficiaries_customer ON beneficiaries (customer_id);

-- ----------------------------------------------------------------------------
-- audit_logs: immutable record of every state change. 'details' is JSONB so we
-- can store an arbitrary, queryable snapshot of what changed.
-- ----------------------------------------------------------------------------
CREATE TABLE audit_logs (
    id          BIGSERIAL PRIMARY KEY,
    actor       VARCHAR(64),                 -- username or "system"
    action      VARCHAR(64)  NOT NULL,       -- e.g. ACCOUNT_OPENED, TRANSFER
    entity_type VARCHAR(64),                 -- e.g. ACCOUNT, TRANSACTION
    entity_id   VARCHAR(64),
    details     JSONB,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_actor   ON audit_logs (actor);
CREATE INDEX idx_audit_action  ON audit_logs (action);
CREATE INDEX idx_audit_created ON audit_logs (created_at);

-- ----------------------------------------------------------------------------
-- fraud_assessments: the fraud-scoring result attached to a transaction.
-- 'reasons' is JSONB - a list of human-readable reason strings from the
-- scoring strategies.
-- ----------------------------------------------------------------------------
CREATE TABLE fraud_assessments (
    id             BIGSERIAL PRIMARY KEY,
    transaction_id BIGINT       REFERENCES transactions (id),
    score          NUMERIC(5,4) NOT NULL,    -- 0.0000 .. 1.0000
    decision       VARCHAR(16)  NOT NULL,    -- ALLOW | REVIEW | BLOCK
    reasons        JSONB,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_fraud_decision CHECK (decision IN ('ALLOW', 'REVIEW', 'BLOCK'))
);

CREATE INDEX idx_fraud_txn ON fraud_assessments (transaction_id);
