package com.securebank.ai;

import com.securebank.ai.provider.DeterministicAiProvider;
import com.securebank.ai.provider.LlmAiProvider;
import com.securebank.domain.Account;
import com.securebank.domain.Transaction;
import com.securebank.domain.enums.TransactionType;
import com.securebank.dto.AiDtos.CategoryBreakdown;
import com.securebank.dto.AiDtos.SpendingInsightsResponse;
import com.securebank.exception.ResourceNotFoundException;
import com.securebank.repository.AccountRepository;
import com.securebank.repository.TransactionRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.context.MessageSource;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Produces spending insights for a customer: a category breakdown plus a
 * natural-language summary.
 *
 * <p>The numeric breakdown is computed deterministically from the ledger (no AI
 * needed). The NL summary is generated by the AI provider when available, with a
 * localized template fallback otherwise - the same graceful-degradation pattern
 * used by the assistant. Categorization here is a simple keyword bucket over the
 * transaction description; in a real bank this would be a richer merchant-category
 * mapping.</p>
 */
@Service
@RequiredArgsConstructor
public class SpendingInsightsService {

    private static final String SYSTEM_PROMPT =
            "You are a personal-finance assistant. Given a customer's spending "
            + "breakdown by category, write a short, friendly 2-3 sentence summary "
            + "highlighting where most money went and one practical observation. "
            + "Do not invent numbers beyond those provided.";

    private final AccountRepository accountRepository;
    private final TransactionRepository transactionRepository;
    private final LlmAiProvider llmProvider;
    private final DeterministicAiProvider deterministicProvider;
    private final MessageSource messageSource;

    /**
     * Compute insights for all of the customer's accounts over the last N days.
     * Only money LEAVING the account (withdrawals + outgoing transfers) counts as
     * spending.
     */
    @Transactional(readOnly = true)
    public SpendingInsightsResponse forCustomer(String username, int days) {
        List<Account> accounts = accountRepository.findByCustomerUserUsername(username);
        if (accounts.isEmpty()) {
            throw new ResourceNotFoundException("error.customer.notFound");
        }
        String currency = accounts.get(0).getCurrency();
        Instant since = Instant.now().minus(days, ChronoUnit.DAYS);

        // Gather outgoing transactions across the customer's accounts.
        List<Transaction> spending = new ArrayList<>();
        for (Account a : accounts) {
            transactionRepository.findTop50ByAccountIdOrderByCreatedAtDesc(a.getId()).stream()
                    .filter(t -> t.getCreatedAt() != null && t.getCreatedAt().isAfter(since))
                    .filter(this::isOutgoing)
                    .forEach(spending::add);
        }

        // Bucket by category and total.
        Map<String, List<Transaction>> byCategory = spending.stream()
                .collect(Collectors.groupingBy(t -> categoryOf(t.getDescription())));

        List<CategoryBreakdown> breakdown = byCategory.entrySet().stream()
                .map(e -> new CategoryBreakdown(
                        e.getKey(),
                        e.getValue().stream().map(Transaction::getAmount)
                                .reduce(BigDecimal.ZERO, BigDecimal::add),
                        e.getValue().size()))
                .sorted(Comparator.comparing(CategoryBreakdown::total).reversed())
                .toList();

        BigDecimal totalSpent = breakdown.stream()
                .map(CategoryBreakdown::total)
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        String[] summaryAndProvider = buildSummary(currency, totalSpent, breakdown);
        return new SpendingInsightsResponse(currency, totalSpent, breakdown,
                summaryAndProvider[0], summaryAndProvider[1]);
    }

    // ---- helpers -----------------------------------------------------------

    private boolean isOutgoing(Transaction t) {
        return t.getType() == TransactionType.WITHDRAWAL
                || t.getType() == TransactionType.TRANSFER;
    }

    /** Map a free-text description to a coarse spending category. */
    private String categoryOf(String description) {
        if (description == null) return "Other";
        String d = description.toLowerCase();
        if (d.contains("grocer") || d.contains("food") || d.contains("restaurant")) return "Food & Groceries";
        if (d.contains("electric") || d.contains("bill") || d.contains("utility") || d.contains("water")) return "Utilities";
        if (d.contains("rent") || d.contains("mortgage")) return "Housing";
        if (d.contains("fuel") || d.contains("petrol") || d.contains("uber") || d.contains("travel")) return "Transport";
        if (d.contains("transfer")) return "Transfers";
        return "Other";
    }

    /**
     * Build the NL summary. Returns {@code [summary, provider]}. Tries the LLM
     * (Claude); on unavailability falls back to a localized template so the
     * endpoint always returns a readable summary.
     */
    private String[] buildSummary(String currency, BigDecimal total, List<CategoryBreakdown> breakdown) {
        Locale locale = LocaleContextHolder.getLocale();

        if (breakdown.isEmpty()) {
            return new String[]{
                    messageSource.getMessage("insights.summary.empty", null,
                            "No spending recorded.", locale),
                    "template"};
        }

        // Attempt the LLM if available.
        if (llmProvider.isAvailable()) {
            String prompt = renderPromptData(currency, total, breakdown);
            String answer = llmProvider.complete(SYSTEM_PROMPT, prompt);
            if (!LlmAiProvider.UNAVAILABLE_SENTINEL.equals(answer)) {
                return new String[]{answer, llmProvider.name()};
            }
        }

        // Deterministic localized template fallback.
        String top = breakdown.get(0).category();
        String summary = messageSource.getMessage(
                "insights.summary.template",
                new Object[]{total, currency, breakdown.size(), top},
                locale);
        return new String[]{summary, deterministicProvider.name()};
    }

    /** Render the breakdown as plain text for the LLM prompt. */
    private String renderPromptData(String currency, BigDecimal total, List<CategoryBreakdown> breakdown) {
        StringBuilder sb = new StringBuilder();
        sb.append("Total spent: ").append(total).append(' ').append(currency).append('\n');
        sb.append("By category:\n");
        for (CategoryBreakdown c : breakdown) {
            sb.append("- ").append(c.category()).append(": ")
                    .append(c.total()).append(' ').append(currency)
                    .append(" (").append(c.count()).append(" transactions)\n");
        }
        return sb.toString();
    }
}
